name: greet-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  greet-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world actions steps
        id: hello
        uses: infinity-intellect/hello-github-actions@v1.1.1
        with:
          who-to-greet: 'Infinity Intellect'
      - name: Get the output time
        run: echo "The time was ${{steps.hello.outputs.time}}"
