name: greet-action
on: issue_comment
jobs:
  pr_commented:
    name: PR Comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: infinity-intellect/hello-github-actions@v2.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment_starter: 'Thanks for commenting on this PR.'
  issue_commented:
    name: Issue Comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: infinity-intellect/hello-github-actions@v2.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment_starter: 'We appreciate you taking your time to comment on this issue.'


